version: "3.7"

volumes:
  openldap:
  phpldapadmin:
  redis:
  apiauthuser:

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    hostname: openldap
    ports:
      - "${LDAP_PORT}:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${DC1}
      - LDAP_DOMAIN=${DOMAIN}
      - LDAP_ADMIN_USERNAME=${ADMINUSER}
      - LDAP_ADMIN_PASSWORD=${PASSWORD}
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=${DC1},dc=${DC2}"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=${DOMAIN}.ca.crt
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - openldap

  apiauthuser:
    build:
      context: apiauth-javascript/
    container_name: apiauthuser
    hostname: apiauthuser
    ports:
      - "${PORT}:${PORT}"
    networks:
      - openldap

networks:
  openldap:
    driver: bridge
