NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/larmdev-ga-7054-fabric-ca-tls.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/larmdev-ga-7054-fabric-ca-tls.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/larmdev-ga-7054-fabric-ca-tls.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/larmdev-ga-7054-fabric-ca-tls.pem
        OrganizationalUnitIdentifier: orderer
