FROM alpine:3.12

WORKDIR /script

COPY package*.json ./

RUN apk add --update nodejs npm && apk add --update npm && npm install nodemon

RUN npm install

COPY . .

EXPOSE 3500

CMD ["npm","run","serve"]